//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplicationSecondGit.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edu.softserve.com/", ConfigurationName="ServiceReference.CalcSEI")]
    public interface CalcSEI {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:Hello", ReplyAction="*")]
        ConsoleApplicationSecondGit.ServiceReference.helloResponse hello(ConsoleApplicationSecondGit.ServiceReference.hello request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Hello", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplicationSecondGit.ServiceReference.helloResponse> helloAsync(ConsoleApplicationSecondGit.ServiceReference.hello request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplicationSecondGit.ServiceReference.addResponse add(ConsoleApplicationSecondGit.ServiceReference.add request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplicationSecondGit.ServiceReference.addResponse> addAsync(ConsoleApplicationSecondGit.ServiceReference.add request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hello {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://edu.softserve.com/", Order=0)]
        public ConsoleApplicationSecondGit.ServiceReference.helloBody Body;
        
        public hello() {
        }
        
        public hello(ConsoleApplicationSecondGit.ServiceReference.helloBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public helloBody() {
        }
        
        public helloBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public ConsoleApplicationSecondGit.ServiceReference.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(ConsoleApplicationSecondGit.ServiceReference.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class add {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public add() {
        }
        
        public add(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public addResponse() {
        }
        
        public addResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSEIChannel : ConsoleApplicationSecondGit.ServiceReference.CalcSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSEIClient : System.ServiceModel.ClientBase<ConsoleApplicationSecondGit.ServiceReference.CalcSEI>, ConsoleApplicationSecondGit.ServiceReference.CalcSEI {
        
        public CalcSEIClient() {
        }
        
        public CalcSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplicationSecondGit.ServiceReference.helloResponse ConsoleApplicationSecondGit.ServiceReference.CalcSEI.hello(ConsoleApplicationSecondGit.ServiceReference.hello request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string arg0) {
            ConsoleApplicationSecondGit.ServiceReference.hello inValue = new ConsoleApplicationSecondGit.ServiceReference.hello();
            inValue.Body = new ConsoleApplicationSecondGit.ServiceReference.helloBody();
            inValue.Body.arg0 = arg0;
            ConsoleApplicationSecondGit.ServiceReference.helloResponse retVal = ((ConsoleApplicationSecondGit.ServiceReference.CalcSEI)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplicationSecondGit.ServiceReference.helloResponse> ConsoleApplicationSecondGit.ServiceReference.CalcSEI.helloAsync(ConsoleApplicationSecondGit.ServiceReference.hello request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplicationSecondGit.ServiceReference.helloResponse> helloAsync(string arg0) {
            ConsoleApplicationSecondGit.ServiceReference.hello inValue = new ConsoleApplicationSecondGit.ServiceReference.hello();
            inValue.Body = new ConsoleApplicationSecondGit.ServiceReference.helloBody();
            inValue.Body.arg0 = arg0;
            return ((ConsoleApplicationSecondGit.ServiceReference.CalcSEI)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplicationSecondGit.ServiceReference.addResponse ConsoleApplicationSecondGit.ServiceReference.CalcSEI.add(ConsoleApplicationSecondGit.ServiceReference.add request) {
            return base.Channel.add(request);
        }
        
        public int add(int arg0, int arg1) {
            ConsoleApplicationSecondGit.ServiceReference.add inValue = new ConsoleApplicationSecondGit.ServiceReference.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            ConsoleApplicationSecondGit.ServiceReference.addResponse retVal = ((ConsoleApplicationSecondGit.ServiceReference.CalcSEI)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplicationSecondGit.ServiceReference.addResponse> ConsoleApplicationSecondGit.ServiceReference.CalcSEI.addAsync(ConsoleApplicationSecondGit.ServiceReference.add request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplicationSecondGit.ServiceReference.addResponse> addAsync(int arg0, int arg1) {
            ConsoleApplicationSecondGit.ServiceReference.add inValue = new ConsoleApplicationSecondGit.ServiceReference.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ConsoleApplicationSecondGit.ServiceReference.CalcSEI)(this)).addAsync(inValue);
        }
    }
}
